# Generated by Django 3.2.15 on 2022-09-14 23:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='uploads/songs/images'),
        ),
    ]
