# Generated by Django 3.2.15 on 2022-09-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_gallery', '0002_auto_20220915_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='music',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
