# Generated by Django 3.2.15 on 2022-09-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_gallery', '0003_auto_20220915_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_url',
        ),
    ]
